---
cluster_name: "${CLUSTER_NAME}"
kubeconfig_path: "./kubeconfig"
k3s_version: v1.27.3+k3s1
use_ssh_agent: false
ssh_port: 22
public_ssh_key_path: ${SSH_PUBLIC_KEY_PATH}
private_ssh_key_path: ${SSH_PRIVATE_KEY_PATH}
ssh_allowed_networks:
  - "0.0.0.0/0"
api_allowed_networks:
  - "0.0.0.0/0"
private_network_subnet: ${VPC_SUBNET}
schedule_workloads_on_masters: true # not recommended but cost constraints...
image: 103908130 # ubuntu 22.04 arm
cloud_controller_manager_manifest_url: "https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/download/v1.16.0/ccm-networks.yaml"
csi_driver_manifest_url: "https://raw.githubusercontent.com/hetznercloud/csi-driver/v2.3.2/deploy/kubernetes/hcloud-csi.yml"
system_upgrade_controller_manifest_url: "https://raw.githubusercontent.com/rancher/system-upgrade-controller/master/manifests/system-upgrade-controller.yaml"
masters_pool:
  instance_type: cax11
  instance_count: 1
  location: "${LOCATION}"
worker_node_pools:
- name: small-static
  instance_type: cax11
  instance_count: 2
  location: "${LOCATION}"

- name: big-autoscaled
  instance_type: cax11
  instance_count: 2
  location: "${LOCATION}"
  autoscaling:
    enabled: true
    min_instances: 0
    max_instances: 3